### ISSUE TITLE
How do I use the separation feature?  

### ISSUE THREAD

**Issue by zxxwxyyy** [gladia-research-group/multi-source-diffusion-models#6]
Hi, love the model – super cool stuff! Thank you for open-source the code!!

I was playing around with the notebook demos and couldn't find any demos on the **separation feature**. Really keen on trying that out. Would you kindly point me in the right direction or share a quick how-to?

Thank you so much!

**Comment by Logicino** [comment]
Hello, have you solved this problem? I run into the same problem
I tried to import the "MSDMSeparator" like below
```
from main.separation import MSDMSeparator

num_steps = 20

import soundfile as sf
audio, sr = sf.read("mix.wav")
print(type(audio))
audio = torch.from_numpy(audio.T)

schedule = KarrasSchedule(sigma_min=1e-4, sigma_max=20.0, rho=7)(num_steps, DEVICE)
separator = MSDMSeparator(model=model, stems=[], sigma_schedule=schedule)
separator.separate(audio)
```
however it comes with problems:
<img width="467" alt="image" src="https://github.com/gladia-research-group/multi-source-diffusion-models/assets/26953324/d51be6d2-ea41-42bb-badd-aac339e8a162">
due to the `batch_size, _, length_samples = mixture.shape`
I don't understand what shape should the mixture be
How did you solve the problem? I really appreciate it! Thank you!
